version: "3.8"

services:

  handler:
    image: "node:15.10"
    volumes:
    - "./projects/handler:/app"
    ports:
    - "80:3000"
    working_dir: "/app"
    environment:
      PORT: "3000"
    command: ["npm", "run", "watch"]
